#!/bin/sh
# ROCEOS K50S Official Network Interface Mapping Specification (Extracted from 原厂 v220307)

. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

board_config_update
board=$(board_name)

case "$board" in
*)
	# ROCEOS K50S 原厂网口绝对定义：WAN 口为 eth0，LAN 口为 eth1 eth2 eth3 eth4
	ucidef_set_interfaces_lan_wan 'eth1 eth2 eth3 eth4' 'eth0'
	;;
esac

board_config_flush

exit 0

