#!/bin/sh
# ROCEOS K50S (RK3568) Official Network Interface Mapping Specification

. /lib/functions/uci-defaults.sh

board_config_update
board=$(board_name)

case "$board" in
*)
	# 依照 ROCEOS 官网规格：
	# ETH0, ETH1, ETH2 (2.5G) 分配为 LAN 局域网接口
	# ETH3 (1G) 分配为 WAN 广域网接口
	ucidef_set_interfaces_lan_wan "eth0 eth1 eth2" "eth3"
	;;
esac

board_config_flush

exit 0
